### ISSUE TITLE
Shading?

### ISSUE THREAD

**Issue by christopher-cudennec** [dropwizard/logback-throttling-appender#99]
Hej Dropwizard team!

I'm currently looking into an issue in our open source project [sda-dropwizard-commons](https://github.com/SDA-SE/sda-dropwizard-commons/). I'm not yet sure what the problem is but would like to understand your component a little better:

I saw that you create an "uber Jar" by shading several dependencies into your artifact. Most dependencies seem to be relocated in this process but not all. 

Why did you keep the package "javax.annotation" as it is but relocate the others? The package contains some of the classes of JSR305. Why don't you use Findbugs' JSR305 implementation?

Why do you need shading at all? I couldn't tell exactly why you need the classes since you don't need them in your imports.

For background information:
We use a "duplicate classes" test in our project that detects duplicate classes in different artifacts. It compains about classes like `CheckForNull` which we pull in from different sources.

Thanks for getting more information!

Cheers,

Christopher

**Comment by joschi** [comment]
> Why did you keep the package "javax.annotation" as it is but relocate the others?

The simple answer is that it was forgotten in the list and it was introduced as a transitive dependency in [logback-throttling-appender 1.1.4](https://github.com/dropwizard/logback-throttling-appender/releases/tag/logback-throttling-appender-1.1.4) via Google Guava 31.0.

> Why do you need shading at all?

We're shading the transitive dependencies so that this project can be used in projects which don't want to include Google Guava.

The shaded JAR is minimized, so only the required classes are part of the artifact, see [`<minimizeJar>`](https://maven.apache.org/plugins/maven-shade-plugin/shade-mojo.html#minimizeJar).

**Comment by christopher-cudennec** [comment]
Thanks for fixing it so quickly! 🌷
